### ISSUE TITLE
YSE engine init unsuccessfully after close 

### ISSUE THREAD

**Issue by niujingqian** [yvanvds/yse-soundengine#10]
my code:
YSE:System().init();
create Sound........
YSE::System().close();
all go well;
I open YSE engine again
YSE::System().init();
create Sound()....
Sound can not play.
Why??
Thanks a lot!

/////////////////////////////////////////////////
void go()
{
YSE::System().init();

YSE::System().close();

/////////////////////////////////////////////

**Comment by yvanvds** [comment]
I guess something cannot be initialized twice. But there's no reason to do that. Use init when you start your application, use close when you shut it down. You don't have to close the engine between playing sounds.

**Comment by niujingqian** [comment]
ATL control belong to a web page,the web page has a control in it,the control can be closed.every web page is a process. Process is not closed when closing a control

**Comment by yvanvds** [comment]
Better close this because i have no clue at all what this is about :-)
