### ISSUE TITLE
YSE engine init unsuccessfully after close 

### ISSUE THREAD

**Issue by niujingqian** [yvanvds/yse-soundengine#11]
my code:
YSE:System().init();
create Sound........
YSE::System().close();
all go well;
I open YSE engine again
YSE::System().init();
create Sound()....
Sound can not play.
Why??
Thanks a lot!

/////////////////////////////////////////////////
void go()
{
	YSE::System().init();
	YSE::System().close();
	YSE::System().init();
	createSound..........
	can not work!!!
}
/////////////////////////////////////////////

**Comment by yvanvds** [comment]
duplicate

**Comment by niujingqian** [comment]
I use the YSE sound engine in ATL control,
ATL ActiveX would create and destroy repeatedly.
YSE engine work well at first time,
but not play sound at second time ...
//////code
XXXControl::OnCreate()
{
      YSE::System().init();
}
XXXControl::update()
{
      YSE::System().update();
}
XXXControl::OnDestroy()
{
      YSE::System().close();
}

**Comment by niujingqian** [comment]
thanks!
