### ISSUE TITLE
YSE errors when used within custom static library

### ISSUE THREAD

**Issue by cappah** [yvanvds/yse-soundengine#13]
I'm trying to use YSE within a static game engine library I'm writing, but when it comes to compiling, I get: **C2059 syntax error:** '__cdecl'  synth.hpp line 37 (CALLBACK,)
**C3805 '__cdecl':** unexpected token, expected either '}' or a ',' at the same line in synth.hpp
**C2059 syntax error** for "RELATIVE" at line 36 in sound.hpp
And both having errors (abc) saying "expected an identifier.

To make sure that the YSE library worked, I created a simple console application just to play a sound and it worked flawlessly. So I don't know what the issue may be when I try to use it with my library. The only other libraries in my engine are glm, Bullet Physics, Assimp and Vulkan.

**Comment by cappah** [comment]
**Update:**
I finally got it to work in my static library by changing "CALLBACK" and "RELATIVE" to CALLBACK_YSE and RELATIVE_YSE.

So if this is a problem with others and you get the same errors, this is a possible solution.

**Comment by yvanvds** [comment]
I think we can close this now :-)
