### ISSUE TITLE
Add reverb on wav file

### ISSUE THREAD

**Issue by yangshulin2019** [yvanvds/yse-soundengine#20]
I am working on a Android project to add reverb to wav file or PCM io stream. I find it is hard for yse-soundengine to realize it, because it is seems like a audio play engine. The DSP code is hard to decoupling, can you give me some help to realize it?

**Comment by yvanvds** [comment]
I'm not really sure what you mean. Are you trying to add reverb to a saved file? Yse is intended for live audio rendering, not for adding effects and writing them to disk.

**Comment by yangshulin2019** [comment]
Yes, I want to add effect on a saved file. The android platform SDK has already give powerful function of live audio rendering for audio fx. But the file readering is lacking. I am developing a Karaoke app and need this function.

**Comment by yvanvds** [comment]
In that case, YSE is not what you are looking for.
