### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by adderly** [yvanvds/yse-soundengine#4]
I see that linux is supported and everything, sadly in the releases section there is no yse linux binary. And the build scripts are not provided. Am i missing something.

**Comment by yvanvds** [comment]
Hi

I'm not sure if I can create a universal linux library, what with all the different distributions and such? I'm  no expert in that. What I can do is create the needed build scripts. I should have done that long ago but somehow it never happened.

I'll try to do that this weekend and inform you when they'll be available.

**Comment by adderly** [comment]
I see, well universal binary is hard. It all depends on the type of dependencies needed. Ok, i'll wait paciently :dancer:

**Comment by yvanvds** [comment]
Hello again.

I just added a linux build script. I tested this on ubuntu 15.04. I've also updated the manual (can be found in the release downloads) with a section on compiling on linux.

This is only tested on my own computer so if anything is missing, please let me know. I can imagine i had most dependencies already in place.

**Comment by adderly** [comment]
Thanks it worked. Running Arch linux here.
